### ISSUE TITLE
Update of RPE

### ISSUE THREAD

**Issue by liuyueChang** [HKUST-Aerial-Robotics/SIMPL#18]
Thank you for your outstanding work ! 

Why is it necessary to update the RPE, and what idea inspired this design?

**Comment by MasterIzumi** [comment]
Thanks!
Intuitively, we can regard the RPE as the edge feature, and the scene-centric token as the node feature. Updating the RPE equals to updating the edge feature. Meanwhile, this module brings more learnable parameters and achieves better overall results.
