### ISSUE TITLE
some redundant code here？

### ISSUE THREAD

**Issue by Chnnnne** [HKUST-Aerial-Robotics/SIMPL#7]
the line 125`agent_traj[:, 0:2] = agent_traj[:, 0:2]` of /SIMPL/data_argo/argo_preprocess.py on branch-main, is it meaningless?

**Comment by MasterIzumi** [comment]
@Chnnnne Yes, it is redundant. Thanks for your reminder, I will clean it soon.

**Comment by Chnnnne** [comment]
There are also lines 166 and 167 of the same py file.
btw👨‍🔧This is the first autonomous driving code I've been reading, so I'm paying close attention to the details😂

**Comment by MasterIzumi** [comment]
@Chnnnne Yep, L167 is also redundant.

If you have any questions, please feel free to contact me :)
