### ISSUE TITLE
target-centric and scene-centric

### ISSUE THREAD

**Issue by lsr12345** [HKUST-Aerial-Robotics/SIMPL#8]
Congratulations on the excellent work! I have noticed that in the Argoverse2 data processing, a target-centric coordinate rotation method is utilized instead of a scene-centric approach. I am curious about the impact of this choice on the performance of multi-agent prediction as demonstrated in the paper.
Specifically, I would like to inquire:
If there have been any comparative analyses between target-centric and scene-centric coordinate rotation methods, could you please share the findings or insights?
Thank you for your attention to this matter, and I look forward to any clarifications or additional information you can provide.

**Comment by lsr12345** [comment]
THX！

**Comment by penglo** [comment]
> Congratulations on the excellent work! I have noticed that in the Argoverse2 data processing, a target-centric coordinate rotation method is utilized instead of a scene-centric approach. I am curious about the impact of this choice on the performance of multi-agent prediction as demonstrated in the paper. Specifically, I would like to inquire: If there have been any comparative analyses between target-centric and scene-centric coordinate rotation methods, could you please share the findings or insights? Thank you for your attention to this matter, and I look forward to any clarifications or additional information you can provide.

Hello, I also have some questions about coordinate transformation as a beginner. May I ask you some questions about it? If it's convenient for you, could you please leave your email so I can contact you? I would greatly appreciate it. My email is lipl23@mails.jlu.edu.cn.
